feat(user): user crud finally
GabrielNogueiraBR/nextfood-backend pull request #4
Opened 2022-05-13 22:13 UTC by gaabrielferraz

add PR crud user

2022-05-13 23:22 UTC, VitorGois requested changes

2022-05-13 23:22 UTC, VitorGois commented on source/user/user.dto.ts
> +  @IsOptional() @IsNumberString()
Não vai ser mais `@IsNumberString()`, e sim utilizar agora `@IsUUUID()`, por conta da coluna id do banco de dados.

2022-05-13 23:22 UTC, VitorGois commented on source/user/user.dto.ts
> +  @IsString()
Aqui arrumar o alinhamento, e utilizar `@IsUUID()`

2022-05-13 23:22 UTC, VitorGois commented on source/user/user.dto.ts
> +  @IsString()
Aqui utilizar `@IsUUID()`

2022-05-14 11:41 UTC, gaabrielferraz commented on source/user/user.dto.ts
> +  @IsString()
@IsUUID() implementado no código.

2022-05-14 11:41 UTC, gaabrielferraz commented on source/user/user.dto.ts
> +  @IsString()
@IsUUID() implementado no código.

2022-05-14 11:41 UTC, gaabrielferraz commented on source/user/user.dto.ts
> +  @IsOptional() @IsNumberString()
@IsUUID() alterado no código.

2022-05-14 14:51 UTC, VitorGois approved these changes

2022-05-14 14:51 UTC, VitorGois commented
Bala de mais, parabéns!

2022-05-17 23:08 UTC, merged