Produtos
GabrielNogueiraBR/nextfood-backend pull request #8
Opened 2022-05-19 00:21 UTC by VitorGois

2022-05-19 13:33 UTC, GabrielNogueiraBR commented
@VitorGois essa branch está com algum conflito, será que você poderia revisar isso antes da gente aprovar a PR?

2022-05-19 15:56 UTC, GabrielNogueiraBR requested changes
Apenas verificar a questão da foto do produto que eu achei que faltou.

2022-05-19 15:56 UTC, GabrielNogueiraBR commented on source/product/product.dto.ts
> +  public amountP: string;
Talvez aqui eu pensaria em um nome melhor para ficar mais autoexplicativo.

2022-05-19 15:56 UTC, GabrielNogueiraBR commented on source/product/product.entity.ts
> +}
Acredito que aqui faltou a informação da foto do produto que havíamos conversado na segunda feira que seria uma string com a URL da foto.

2022-05-19 15:57 UTC, GabrielNogueiraBR commented on source/product/product.entity.ts
> +}
![image](https://user-images.githubusercontent.com/30303558/169344704-db94b90b-bf2b-470b-926c-970ca9336552.png)

2022-05-19 15:57 UTC, GabrielNogueiraBR commented on source/product/product.entity.ts
> +}
![image](https://user-images.githubusercontent.com/30303558/169344793-5441c175-0a29-4be6-ba66-57035b0cb19e.png)

2022-05-20 01:07 UTC, VitorGois commented on source/product/product.entity.ts
> +}
done

2022-05-20 01:07 UTC, VitorGois commented on source/product/product.dto.ts
> +  public amountP: string;
done

2022-05-20 12:34 UTC, GabrielNogueiraBR approved these changes
Boa, agora parece estar tudo certo!

2022-05-20 21:42 UTC, merged